######################################################
# General Configuration
######################################################

# Tag of produced result files
Tag: result

# Path to store the result files
ResultPath: ../result/

######################################################
# Theory Configuration
######################################################

# Order of the used theory (NNLLNNLO,NLLNLO are options)
TheoryOrder: ['NNLLNNLO', 'NS22NNLO', 'NS27NNLO', 'NS28NNLO', 'NS78NNLO', 'NS88NNLO']
SubLeadTheoryOrder: 'SSF27_10575'

# Tag of used Theory
TheoryTag: 'expx3'
SubleadingTheoryTag: 'SSF27'

# Path to the dictionaries containing the used theory
TheoryPath: ../theory/theory_dictionary_expx3
SubleadingTheoryPath: ../theory/theory_dictionary_SSF27

# Path for constraints and moments
TheoryMomentsPath: ../theory/Fmn_moments

######################################################
# Measurement Configuration
######################################################

# Path to measurement dictionary
MeasurementPath: ../data/exp_data

## Which measurements should be included in the fit?
KeyOrder: ["belle", "babar_hadtag", "babar_incl"]
#"babar_sem" 

# Only takes the values from index 'Minimum' of the experimental data
Minimum:
  belle: 6
  babar_incl: 3

# Scale
Scale:
  belle: 2

######################################################
# Fit Configuration
######################################################

# Fit expansion 
BasisExpansion: '0575'
SubLeadBasisExpansion: '10575'

# Fit Variables Naming
FitVars: ["norm", "a1", "a2", "a3", "a4", "a5"]

## Start values
StartValues: [0.00506919, 0.0, 0.0798100, 0.0870341, 0.0250290, 0.0]

# How many Parameters do you want ?
NumbPar: 6

######################################################
# Theory Input Values 
######################################################

Constants:
  # Constants for mB, Lambda2, rho2
  mB: 5.279
  La2: 0.12
  rho2: -0.05

  # Normalization value: 10^4 G_F^2 alpha_em 4.7^3 / (32 pi^4) / (hbar/tauB) (using PDG 2018)
  N0: 794.0705566209606
  # Used value for |Vtb Vts*| (from PDG 2018 global fit)
  VtbVts: 0.04129300965

  # Wilson coefficients for non 7 contributions
  # Cj C7 with Cj=-2(C2 - C1/6)
  C2C7: -2.109974309809888
  # CiCj=(C2 - C1/6)^2
  C2C2: 1.1129978970144285
  # C7 Cj with Cj=-2*C8, - accounts for sign of C7
  C8C7: 0.2760118962325344
  # CiCj with Cj=C8^2
  C8C8: 0.019045641715469835
  # CiCj=2(C2 - C1/6)*C8
  C2C8: -0.29118900512628015

######################################################
#  Subleading theory coefficients 
######################################################

## Default value for d2 is 0
SubLeadCoefficients: [0.]